/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HybridVarOrderHeap */

#ifndef _Included_HybridVarOrderHeap
#define _Included_HybridVarOrderHeap
#ifdef __cplusplus
extern "C" {
#endif
#undef HybridVarOrderHeap_serialVersionUID
#define HybridVarOrderHeap_serialVersionUID 1LL
#undef HybridVarOrderHeap_VAR_RESCALE_FACTOR
#define HybridVarOrderHeap_VAR_RESCALE_FACTOR 1.0E-100
#undef HybridVarOrderHeap_VAR_RESCALE_BOUND
#define HybridVarOrderHeap_VAR_RESCALE_BOUND 1.0E100
/*
 * Class:     HybridVarOrderHeap
 * Method:    runWalkSat
 * Signature: ([C[CLDataInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_HybridVarOrderHeap_runWalkSat
  (JNIEnv *, jclass, jcharArray, jcharArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
